INSERT INTO tt_app_activity VALUES (17, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '17');
INSERT INTO tt_app_activity VALUES (18, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '18');
INSERT INTO tt_app_activity VALUES (19, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '19');
INSERT INTO tt_app_activity VALUES (20, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '20');
INSERT INTO tt_app_activity VALUES (21, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '21');
INSERT INTO tt_app_activity VALUES (22, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '22');
INSERT INTO tt_app_activity VALUES (23, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (23, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (24, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '24');
INSERT INTO tt_app_activity VALUES (25, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '25');
INSERT INTO tt_app_activity VALUES (26, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '26');
INSERT INTO tt_app_activity VALUES (27, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '27');
INSERT INTO tt_app_activity VALUES (28, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '28');
INSERT INTO tt_app_activity VALUES (29, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '29');
INSERT INTO tt_app_activity VALUES (30, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '30');
INSERT INTO tt_app_activity VALUES (31, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '31');
INSERT INTO tt_app_activity VALUES (32, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '32');
INSERT INTO tt_app_activity VALUES (33, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '33');
INSERT INTO tt_app_activity VALUES (34, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '34');
INSERT INTO tt_app_activity VALUES (35, '30', 'L3', 'Interval',  'Snow Ski Skate', '4', '35');
INSERT INTO tt_app_activity VALUES (36, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '36');
INSERT INTO tt_app_activity VALUES (37, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '37');
INSERT INTO tt_app_activity VALUES (38, '30', 'L3', 'Interval',  'Snow Ski Classic', '4', '38');
INSERT INTO tt_app_activity VALUES (39, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '39');
INSERT INTO tt_app_activity VALUES (40, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '40');
INSERT INTO tt_app_activity VALUES (41, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '41');
INSERT INTO tt_app_activity VALUES (42, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '42');
INSERT INTO tt_app_activity VALUES (43, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '43');
INSERT INTO tt_app_activity VALUES (44, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '44');
INSERT INTO tt_app_activity VALUES (45, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '45');
INSERT INTO tt_app_activity VALUES (46, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '46');
INSERT INTO tt_app_activity VALUES (47, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '47');
INSERT INTO tt_app_activity VALUES (48, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '48');
INSERT INTO tt_app_activity VALUES (49, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '49');
INSERT INTO tt_app_activity VALUES (50, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '50');
INSERT INTO tt_app_activity VALUES (51, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '51');
INSERT INTO tt_app_activity VALUES (52, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '52');
INSERT INTO tt_app_activity VALUES (53, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '53');
INSERT INTO tt_app_activity VALUES (54, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '54');
INSERT INTO tt_app_activity VALUES (55, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '55');
INSERT INTO tt_app_activity VALUES (56, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '56');
INSERT INTO tt_app_activity VALUES (57, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '57');
INSERT INTO tt_app_activity VALUES (58, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '58');
INSERT INTO tt_app_activity VALUES (59, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '59');
INSERT INTO tt_app_activity VALUES (60, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '60');
INSERT INTO tt_app_activity VALUES (61, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '12');
INSERT INTO tt_app_activity VALUES (62, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '13');
INSERT INTO tt_app_activity VALUES (63, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '14');
INSERT INTO tt_app_activity VALUES (64, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '15');
INSERT INTO tt_app_activity VALUES (65, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '16');
INSERT INTO tt_app_activity VALUES (66, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '12');
INSERT INTO tt_app_activity VALUES (67, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '13');
INSERT INTO tt_app_activity VALUES (68, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '14');
INSERT INTO tt_app_activity VALUES (69, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '15');
INSERT INTO tt_app_activity VALUES (70, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '18');
INSERT INTO tt_app_activity VALUES (71, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '19');
INSERT INTO tt_app_activity VALUES (72, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '20');
INSERT INTO tt_app_activity VALUES (73, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '21');
INSERT INTO tt_app_activity VALUES (74, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '22');
INSERT INTO tt_app_activity VALUES (75, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (76, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (77, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '24');
INSERT INTO tt_app_activity VALUES (78, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '25');
INSERT INTO tt_app_activity VALUES (79, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '26');
INSERT INTO tt_app_activity VALUES (80, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '28');
INSERT INTO tt_app_activity VALUES (81, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '29');
INSERT INTO tt_app_activity VALUES (82, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '30');
INSERT INTO tt_app_activity VALUES (83, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '31');
INSERT INTO tt_app_activity VALUES (84, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '32');
INSERT INTO tt_app_activity VALUES (85, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '33');
INSERT INTO tt_app_activity VALUES (86, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '34');
INSERT INTO tt_app_activity VALUES (87, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '35');
INSERT INTO tt_app_activity VALUES (88, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '36');
INSERT INTO tt_app_activity VALUES (89, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '37');
INSERT INTO tt_app_activity VALUES (90, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '39');
INSERT INTO tt_app_activity VALUES (91, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '40');
INSERT INTO tt_app_activity VALUES (92, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '41');
INSERT INTO tt_app_activity VALUES (93, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '42');
INSERT INTO tt_app_activity VALUES (94, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '43');
INSERT INTO tt_app_activity VALUES (95, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '44');
INSERT INTO tt_app_activity VALUES (96, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '45');
INSERT INTO tt_app_activity VALUES (97, '30', 'L1', 'Warm Up',   'Snow Ski Classic', '4', '46');
INSERT INTO tt_app_activity VALUES (98, '30', 'L4', 'Interval',  'Snow Ski Classic', '4', '47');
INSERT INTO tt_app_activity VALUES (99, '30', 'L1', 'Cool Down', 'Snow Ski Classic', '4', '48');
INSERT INTO tt_app_activity VALUES (100, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '50');
INSERT INTO tt_app_activity VALUES (101, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '51');
INSERT INTO tt_app_activity VALUES (102, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '52');
INSERT INTO tt_app_activity VALUES (103, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '53');
INSERT INTO tt_app_activity VALUES (104, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '54');
INSERT INTO tt_app_activity VALUES (105, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '55');
INSERT INTO tt_app_activity VALUES (106, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '56');
INSERT INTO tt_app_activity VALUES (107, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '57');
INSERT INTO tt_app_activity VALUES (108, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '58');
INSERT INTO tt_app_activity VALUES (109, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '59');
INSERT INTO tt_app_activity VALUES (110, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '17');
INSERT INTO tt_app_activity VALUES (111, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '18');
INSERT INTO tt_app_activity VALUES (112, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '19');
INSERT INTO tt_app_activity VALUES (113, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '20');
INSERT INTO tt_app_activity VALUES (114, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '21');
INSERT INTO tt_app_activity VALUES (115, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '22');
INSERT INTO tt_app_activity VALUES (116, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (117, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '23');
INSERT INTO tt_app_activity VALUES (118, '30', 'L1', 'Warm Up',   'Snow Ski Skate', '4', '24');
INSERT INTO tt_app_activity VALUES (119, '30', 'L4', 'Interval',  'Snow Ski Skate', '4', '25');
INSERT INTO tt_app_activity VALUES (120, '30', 'L1', 'Cool Down', 'Snow Ski Skate', '4', '27');
INSERT INTO tt_app_activity VALUES (121, '30', 'L1', 'Warm Up',   'Run', '4', '28');
INSERT INTO tt_app_activity VALUES (122, '30', 'L4', 'Interval',  'Run', '4', '29');
INSERT INTO tt_app_activity VALUES (123, '30', 'L1', 'Cool Down', 'Run', '4', '30');
INSERT INTO tt_app_activity VALUES (124, '30', 'L1', 'Warm Up',   'Run', '4', '31');
INSERT INTO tt_app_activity VALUES (125, '30', 'L4', 'Interval',  'Run', '4', '32');
INSERT INTO tt_app_activity VALUES (126, '30', 'L1', 'Cool Down', 'Run', '4', '33');
INSERT INTO tt_app_activity VALUES (127, '30', 'L1', 'Warm Up',   'Run', '4', '34');
INSERT INTO tt_app_activity VALUES (128, '30', 'L4', 'Interval',  'Run', '4', '35');
INSERT INTO tt_app_activity VALUES (129, '30', 'L1', 'Cool Down', 'Run', '4', '36');
INSERT INTO tt_app_activity VALUES (130, '30', 'L1', 'Warm Up',   'Run', '4', '38');
INSERT INTO tt_app_activity VALUES (131, '30', 'L4', 'Interval',  'Run', '4', '39');
INSERT INTO tt_app_activity VALUES (132, '30', 'L1', 'Cool Down', 'Run', '4', '40');
INSERT INTO tt_app_activity VALUES (133, '30', 'L1', 'Warm Up',   'Run', '4', '41');
INSERT INTO tt_app_activity VALUES (134, '30', 'L4', 'Interval',  'Run', '4', '42');
INSERT INTO tt_app_activity VALUES (135, '30', 'L1', 'Cool Down', 'Run', '4', '43');
INSERT INTO tt_app_activity VALUES (136, '30', 'L1', 'Warm Up',   'Run', '4', '44');
INSERT INTO tt_app_activity VALUES (137, '30', 'L4', 'Interval',  'Run', '4', '45');
INSERT INTO tt_app_activity VALUES (138, '30', 'L1', 'Cool Down', 'Run', '4', '46');
INSERT INTO tt_app_activity VALUES (139, '30', 'L1', 'Warm Up',   'Run', '4', '47');
INSERT INTO tt_app_activity VALUES (140, '30', 'L4', 'Interval',  'Run', '4', '48');
INSERT INTO tt_app_activity VALUES (141, '30', 'L1', 'Cool Down', 'Run', '4', '50');
INSERT INTO tt_app_activity VALUES (142, '30', 'L1', 'Warm Up',   'Run', '4', '51');
INSERT INTO tt_app_activity VALUES (143, '30', 'L4', 'Interval',  'Run', '4', '52');
INSERT INTO tt_app_activity VALUES (144, '30', 'L1', 'Cool Down', 'Run', '4', '53');
INSERT INTO tt_app_activity VALUES (145, '30', 'L1', 'Warm Up',   'Run', '4', '54');
INSERT INTO tt_app_activity VALUES (146, '30', 'L4', 'Interval',  'Run', '4', '55');
INSERT INTO tt_app_activity VALUES (147, '30', 'L1', 'Cool Down', 'Run', '4', '56');
INSERT INTO tt_app_activity VALUES (148, '30', 'L1', 'Warm Up',   'Run', '4', '57');
INSERT INTO tt_app_activity VALUES (149, '30', 'L4', 'Interval',  'Run', '4', '58');
INSERT INTO tt_app_activity VALUES (150, '30', 'L1', 'Cool Down', 'Run', '4', '59');
INSERT INTO tt_app_activity VALUES (151, '90', 'L2', 'Distance',  'Run', '4', '60');