# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 03:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Intensity',
            fields=[
                ('type', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('RACE', 'RACE')], default='L1', max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('type', models.CharField(choices=[('Distance', 'Distance'), ('Interval', 'Interval'), ('Warm Up', 'Warm Up'), ('Cool Down', 'Cool Down'), ('OD', 'OD'), ('Speed', 'Speed'), ('Time Trial', 'Time Trial'), ('Race', 'Race')], default='Distance', max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('type', models.CharField(choices=[('Strength', 'Strength'), ('Snow Ski Skate', 'Snow Ski Skate'), ('Snow Ski Classic', 'Snow Ski Classic'), ('Roller Ski Skate', 'Roller Ski Skate'), ('Roller Ski Classic', 'Roller Ski Classic'), ('Run', 'Run'), ('Hike', 'Hike'), ('Bounding', 'Bounding'), ('Specific Strength', 'Specific Strength')], default='Run', max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='intensity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.Intensity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='method_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.Method'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.Sport'),
        ),
        migrations.AddField(
            model_name='activity',
            name='training_athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='training_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.Training', to_field='date'),
        ),
    ]
