# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-30 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='training_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='training_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tt_app.Training'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intensity',
            name='type',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('L4', 'L4'), ('Race', 'Race')], default='L1', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='method',
            name='type',
            field=models.CharField(choices=[('Distance', 'Distance'), ('Interval', 'Interval'), ('Warm up', 'Warm Up'), ('Cool Down', 'Cool Down'), ('OD', 'OD'), ('Speed', 'Speed'), ('Time Trial', 'Time Trial'), ('Race', 'Race'), ('Strength', 'Strength')], default='Distance', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Snow Si Skate', 'Snow Ski Skate'), ('Snow Ski Classic', 'Snow Ski Classic'), ('Roller Ski Skate', 'Roller Ski Skate'), ('Roller Ski Classic', 'Roller Ski Classic'), ('Run', 'Run'), ('Hike', 'Hike'), ('Bounding', 'Bounding'), ('Specific Strength', 'Specific Strength')], default='Run', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
