# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-09 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Snow Ski Skate', 'Snow Ski Skate'), ('Snow Ski Classic', 'Snow Ski Classic'), ('Roller Ski Skate', 'Roller Ski Skate'), ('Roller Ski Classic', 'Roller Ski Classic'), ('Run', 'Run'), ('Hike', 'Hike'), ('Bounding', 'Bounding'), ('Specific Strength', 'Specific Strength')], default='Run', max_length=45, primary_key=True, serialize=False),
        ),
    ]
