# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
