# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_app', '0002_auto_20171125_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.IntegerField(),
        ),
    ]
